name: Example
author: MrIzual
api: 2.0.0
load: POSTWORLD
main: Example\Main
version: 1.0.0
description: A Example
commands:
 rules:
  description: "A Rules inforamtion"
  usage: "/rules"
  permission: windyrules.rules

