name: WindyRules
author: MrIzual
api: 2.0.0
load: POSTWORLD
main: WindyRules\Main
version: 1.0.0
description: A Rules Plugin 
commands:
 rules:
  description: "A Rules inforamtion"
  usage: "/rules"
  permission: windyrules.rules

